language: python
services:
- docker
before_install:
- cd app
jobs:
  include:
  - stage: test
    script: python manage.py test
  - stage: build
    script:
    - docker build -t registry.ifflaender-family.de/bladewing/bahnplan .
    - bash ../docker_push
stages:
- test
- build
env:
  global:
    secure: f2Nb/MH02/b3AhaiFMeNSv3TMh8xtD0DPwXlOqq+MrKJ7S8MMgmvXbpF4Xk1wZpSQ1seZgzAsOGYDpvsHmAyFpOrdfYd76SaHLHxmSnOYvFPDivVYODHph4FV9ehvopBcWMS8mMG1fUgpmgBUCHx/y8a3yCHXp90MhAcHFSmi0mCwcV/bPej452wAqxQDdZjKCSHPmkDNluKzA+8O465BECMIO8ZHm9alMaY3grsBgl8MMdKfzzRqOkEMd5PV4Bb/c1aF6Z26oOXPn2RxsXitq/ZxvQSm/hbxodI9QwIYbzg32n5/uUgQfxtPuNw9r7RzCGbz5SVjwIOImM5Q6mqTiNolcm0deHLFDvujtcoeIArkUKRHlf8dTKlhLVkn/hFnSu/1w/REtMVtv8Ax5KMD6FL/g1EqgAVEE0EPAOqX8gGi7QmH5P+CqV6KIugATdY9xEol3tPN/y2lp2R5ohuNnA0/+aloJ3vamEgulW5jef0NabhFc88X0XhPzfmbjG3q/9HDo3MVixtnV2pM1HZH1QcUf6QRyAyHZuIZyqDCdfhxKyXBvUUnmOToB0cBEU9rGTV5UMGJdjAWoxo69lyybZK0sGf/N3EP5ldmzeDES6rdSLVSTM1xkOvxHwx9QmCFbA0Mt8jOkcAAQ28SDoRPtcxGuVYmbpQ1xMl6zbInYA=
