# Generated by Django 3.1.4 on 2021-07-31 22:18

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('abbrev', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinLengthValidator(1)])),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('ownership', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeasingMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('factor_yearly', models.DecimalField(decimal_places=2, max_digits=4)),
                ('factor_weekly', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('course', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='plans/')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('type', models.CharField(choices=[('CG', 'Cargo'), ('LO', 'Local'), ('IC', 'Long Distance')], max_length=2)),
                ('revenue_per_week', models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.route')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('categories', models.ManyToManyField(to='core.WorkshopCategory')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.station')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, unique=True)),
                ('vocal_name', models.CharField(blank=True, max_length=255)),
                ('v_max', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_per_km', models.DecimalField(decimal_places=6, max_digits=12)),
                ('cost_per_hour', models.DecimalField(decimal_places=6, max_digits=12)),
                ('multi_head_limit', models.IntegerField()),
                ('cargo_tons_limit', models.IntegerField()),
                ('workshop_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workshopcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leased_since', models.DateField()),
                ('leasing_mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.leasingmode')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.plan')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='TransportRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('ONCE', 'once'), ('HOURLY', 'hourly'), ('DAILY', 'daily')], max_length=6)),
                ('type', models.CharField(choices=[('PAS', 'PAS'), ('CGO', 'CGO')], max_length=3)),
                ('demand', models.IntegerField()),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(23, 59))),
                ('mon', models.BooleanField()),
                ('tue', models.BooleanField()),
                ('wed', models.BooleanField()),
                ('thu', models.BooleanField()),
                ('fri', models.BooleanField()),
                ('sat', models.BooleanField()),
                ('sun', models.BooleanField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_for', to='core.station')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.line')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_for', to='core.station')),
            ],
        ),
        migrations.CreateModel(
            name='TrackLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=2)),
                ('max_usage_in_minutes', models.IntegerField(default=120)),
                ('time_to_reach_in_minutes', models.IntegerField(default=0)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.station')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tender')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('CG', 'Cargo'), ('LO', 'Local'), ('IC', 'Long Distance')], max_length=2)),
                ('length', models.DecimalField(decimal_places=6, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tracks', models.IntegerField()),
                ('travel_time_in_minutes', models.IntegerField()),
                ('min_speed', models.IntegerField()),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='end_of', to='core.station')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='start_of', to='core.station')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tender')),
            ],
        ),
        migrations.AddField(
            model_name='tender',
            name='workshops',
            field=models.ManyToManyField(to='core.Workshop'),
        ),
        migrations.AddField(
            model_name='plan',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.route'),
        ),
        migrations.AddField(
            model_name='plan',
            name='tender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tender'),
        ),
        migrations.AddField(
            model_name='line',
            name='tender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tender'),
        ),
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=511, null=True)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tender')),
            ],
        ),
    ]
