# Generated by Django 3.1.3 on 2021-01-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210117_1546'),
        ('core', '0002_auto_20210115_1559'),
    ]

    operations = [
    ]
