# Generated by Django 3.1.13 on 2021-10-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20211030_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='description',
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
