# Generated by Django 3.1.3 on 2021-01-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210117_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
