# Generated by Django 3.1.14 on 2022-06-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211031_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='criterions',
            new_name='criteria',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='leased_until',
            field=models.DateField(null=True),
        ),
    ]
