# Generated by Django 3.1.3 on 2021-01-30 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210129_2010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='type',
            new_name='ttype',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='type',
            new_name='vtype',
        ),
        migrations.RemoveField(
            model_name='transportrequirement',
            name='tender',
        ),
        migrations.AddField(
            model_name='transportrequirement',
            name='demand',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportrequirement',
            name='endtime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportrequirement',
            name='frequency',
            field=models.CharField(choices=[('ONCE', 'once'), ('HRLY', 'hourly'), ('DALY', 'daily')], default=0, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportrequirement',
            name='fri',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportrequirement',
            name='mon',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportrequirement',
            name='sat',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportrequirement',
            name='starttime',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportrequirement',
            name='sun',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportrequirement',
            name='thu',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportrequirement',
            name='ttype',
            field=models.CharField(choices=[('PAS', 'PAS'), ('CGO', 'CGO')], default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportrequirement',
            name='tue',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transportrequirement',
            name='wed',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tender')),
            ],
        ),
        migrations.AddField(
            model_name='transportrequirement',
            name='line',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.line'),
            preserve_default=False,
        ),
    ]
