# Generated by Django 3.1.4 on 2021-04-05 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210130_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company'),
        ),
        migrations.AlterField(
            model_name='route',
            name='revenue_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=17, null=True),
        ),
    ]
