# Generated by Django 3.1.4 on 2021-04-24 20:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210424_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default=None, max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
