# Generated by Django 3.1.4 on 2021-05-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210425_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopcategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='workshopcategory',
            name='vocal_name',
        ),
        migrations.AddField(
            model_name='workshopcategory',
            name='category',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='route',
            name='type',
            field=models.CharField(choices=[('CG', 'Cargo'), ('LO', 'Local'), ('IC', 'Long Distance')], max_length=2),
        ),
        migrations.AlterField(
            model_name='track',
            name='ttype',
            field=models.CharField(choices=[('CG', 'Cargo'), ('LO', 'Local'), ('IC', 'Long Distance')], max_length=2),
        ),
    ]
