# Generated by Django 3.1.4 on 2021-06-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210601_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasingmode',
            name='vocal_name',
        ),
    ]
