# Generated by Django 3.1.4 on 2021-06-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20210603_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leasingmode',
            name='factor_weekly',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='leasingmode',
            name='factor_yearly',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
