# Generated by Django 3.1.4 on 2021-06-03 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210603_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='file',
            field=models.FileField(upload_to='plans/'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='tender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tender'),
        ),
    ]
