# Generated by Django 3.1.4 on 2021-06-03 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210604_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='leased_since',
            field=models.DateField(),
        ),
    ]
