# Generated by Django 3.1.4 on 2021-06-03 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210604_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vtype',
            new_name='type',
        ),
    ]
