# Generated by Django 3.1.4 on 2021-06-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210604_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
