# Generated by Django 3.1.4 on 2021-06-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210604_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='ttype',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='track',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
