# Generated by Django 3.1.4 on 2021-06-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210607_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportrequirement',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='transportrequirement',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
