# Generated by Django 3.2.5 on 2021-07-16 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210607_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='course',
            field=models.CharField(default='-default-', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transportrequirement',
            name='end_time',
            field=models.TimeField(default=datetime.time(23, 59)),
        ),
        migrations.AlterField(
            model_name='transportrequirement',
            name='start_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
